FROM python:3.11 as builder-config


ENV CONFIGDIR=/config/poetry
RUN mkdir -p ${CONFIGDIR}
WORKDIR ${CONFIGDIR}

# Configure Poetry
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_NO_INTERACTION=1
RUN curl -sSL https://install.python-poetry.org | python3 -

# Generate apache beam dependencies
COPY ./poetry.lock ./pyproject.toml ./
RUN ~/.local/bin/poetry export --without-hashes --format=requirements.txt > requirements.txt

FROM python:3.11-slim

WORKDIR /app
RUN pip install --upgrade pip

COPY project .
RUN ls
RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 8080

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]