FROM python:3.11-buster as builder

# Install system dependencies
RUN curl -sSL https://install.python-poetry.org | python3

# Configure Poetry
ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

ENV PATH="/root/.local/bin:$PATH"
COPY pyproject.toml poetry.lock ./
RUN touch README.md

# Using cache mount
RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry install  --no-root

FROM python:3.11-slim-buster
ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
COPY . .

EXPOSE 8080

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]